name: "Deploy on Raspberry Pi"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-streamlit:
    name: "🚀 Report Generate"
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: "Move files to /opt/streamlit"
      run: |
        sudo cp -r . /opt/streamlit
